#!/bin/sh
#
# Stop the argus service through upstart.
#
# Deployment triggers shutdown before any start-up
# even on freshly installed hosts, so only run
# shutdown if the service is configured.
#

set -xue

PATH=$PATH:/sbin

initctl emit mention-bot-stop
